## global configs for the app
##
kind: Config

## the spec of this resource
##
spec:

  ## general configs
  ##
  general:

    ## the timezone to run the job in
    ##
    timezone: "UTC"

    ## the number of OutputDatasets which we generate at the same time
    ##
    concurentOutputJobs: 1

  ## spark configs
  ##
  spark:

    ## the spark master to submit jobs to
    ##
    ## EXAMPLE:
    ##   master: "local[4]"
    ##
    master: ""

    ## a map of spark configs
    ##
    configs: {}

    ## a list of jars to add to spark classpath
    ##
    ## NOTE:
    ## - this is used for things like JDBC drivers
    ##
    jars: []

    ## a list of maven coordinates to add to spark classpath
    ##
    packages: []